# Generated by Django 5.0.7 on 2024-07-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
